siliconflow/BizyAir

- __init__.py
- auth.py
- examples/bizyair_kolors_img2img_workflow.json
- examples/bizyair_kolors_text2img_workflow.json
- kolors.py
- llm.py
BizyAir 版本 Kolors，节点使用习惯与 https://github.com/kijai/ComfyUI-KwaiKolorsWrapper 一样。
> Add kolors nodes

- .github/workflows/deploy-docs.yml
- docs/docs/getting-started/quick-start.md
sync with website https://bizyair.siliconflow.cn/ automatically
> Sync docs website

- docs/docs/controlnet-union/introduce.md
- nodes_controlnet_union_sdxl.py
- 新增 controlnet union 的参数说明
- controlnet union node 里的 controlnet_start 和 end 的步长粒度太大，改为 0.01
> refine docs for controlnet union

- docs/docs/others/index.md
- supernode.py
- 后端使用 https://github.com/plemeri/InSPyReNet
- 图片限制说明改为 1536
> update remove background

- .github/workflows/python-format.yml
- auth.py
- image_utils.py
- kolors.py
- llm.py
- nodes_controlnet_union_sdxl.py
- supernode.py
> add python formatter CI

- src/bizyair/configs/flux_dev_config.yaml
内部测试数据：https://github.com/siliconflow/sd-team/issues/450#issue-2444525166
> add_flux_dev_speedup

- src/bizyair/nodes_base.py
> fix bug of category name

- auth.py
- src/bizyair/__init__.py
- src/bizyair/common/__init__.py
- src/bizyair/common/client.py
- 设置 key 前，通过网络校验 key 是否有效
- 设置 key 之后，更新全局使用的 key 变量，这样不需要重启 ComfyUI 再生效
> Refine set the key process

- prestartup_script.py
- requirements.txt
在 ComfyUI 导入 BizyAir 之前，会检查相关依赖是否安装，如果没有安装，自动安装相关依赖。
> check and update requirements automatically

- js/siliconcloud_llm_api.js
- llm.py
- utils.py
This PR introduces support for SiliconFlow's latest VLM (Vision Language Model) API while optimizing existing LLM functionality. Key updates include:
- Added `SiliconCloudVLMAPI` class in `llm.py`, supporting image input and text prompts.
- New node supports model selection, system prompts, user prompts, max tokens, temperature, and other parameter settings.
- Utilizes `encode_comfy_image` function to process input images, supporting multiple image inputs.
- Added `fetch_all_models` function in `llm.py` to retrieve all available models.
- Created separate endpoints for LLM and VLM model fetching: `get_silicon_cloud_llm_models_endpoint` and `get_silicon_cloud_vlm_models_endpoint`.
- Optimized model filtering logic, distinguishing LLM and VLM models based on the presence of "vl" in the …
> Add SiliconCloud VLM API Node

- README.md
- bizyair_example_menu.json
- bizyair_extras/__init__.py
- bizyair_extras/nodes_sd3.py
- examples/bizyair_sd3_5_txt2img.json
- src/bizyair/configs/models.json
- src/bizyair/configs/models.yaml
- src/bizyair/path_utils/path_manager.py
参考：
- comfyui: https://comfyanonymous.github.io/ComfyUI_examples/sd3/#sd35
> Support sd3.5 txt2img

- examples/bizyair_sd3_5_txt2img.json
Modified the layout of sd3_5_txt2img.json but the content remained unchanged
> modified sd3_5_txt2img

- docs/docs/examples/bizyair_anime_image_super_resolution_workflow.json
- docs/docs/examples/bizyair_controlnet_preprocessor_workflow.json
- docs/docs/examples/bizyair_controlnet_union_workflow.json
- docs/docs/examples/bizyair_flux_dev_workflow.json
- docs/docs/examples/bizyair_flux_img2img_workflow.json
- docs/docs/examples/bizyair_flux_joycaption_img2img_workflow.json
- docs/docs/examples/bizyair_flux_pulid.json
- docs/docs/examples/bizyair_flux_schnell_workflow.json
- docs/docs/examples/bizyair_flux_simple_lora_workflow.json
- docs/docs/examples/bizyair_generate_photorealistic_images_workflow.json
- docs/docs/examples/bizyair_kolors_controlnet.json
- docs/docs/examples/bizyair_kolors_inpainting.json
- docs/docs/examples/bizyair_kolors_ipa.json
- docs/docs/examples/bizyair_kolors_txt2img.json
- docs/docs/examples/bizyair_remove_background_workflow.json
- docs/docs/examples/bizyair_sd3_5_txt2img.json
- docs/docs/examples/bizyair_sdxl_InstantID_basic.json
- docs/docs/examples/bizyair_showcase_interior_design.json
- docs/docs/examples/bizyair_showcase_ksampler_controlnet.json
- docs/docs/examples/bizyair_showcase_ksampler_img2img.json
- docs/docs/examples/bizyair_showcase_ksampler_ipadapter.json
- docs/docs/examples/bizyair_showcase_ksampler_lora.json
- docs/docs/examples/bizyair_showcase_ksampler_txt2img.json
- docs/docs/examples/bizyair_showcase_realistic_superresolution.json
- docs/docs/examples/bizyair_showcase_remove_background.json
- docs/docs/examples/bizyair_showcase_shark_submarine.json
- docs/docs/examples/bizyair_text_guided_segment-anything.json
- docs/docs/examples/bizyair_ultimate_sd_upscale.json
在docs目录下新建examples目录，将原Bizyair/examples目录下工作流复制过去
> add examples to docs

- .github/workflows/workflow-ci.yml
- src/bizyair/configs/models.yaml
- tests/test_examples.py
> update CI because of the dialog class from ComfyUI changed

- examples/bizyair_flux_dev_workflow.json
modified:   examples/bizyair_flux_dev_workflow.json (only image size
> modified:examples/bizyair_flux_dev_workflow.json (only image size

- README.md
- bizyair_example_menu.json
- bizyair_extras/__init__.py
- bizyair_extras/nodes_custom_sampler.py
- bizyair_extras/nodes_differential_diffusion.py
- bizyair_extras/nodes_ip2p.py
- examples/bizyair-flux-fill1-inpaint.json
- examples/bizyair-flux1-tools-canny.json
- examples/bizyair-flux1-tools-depth.json
- examples/bizyair-flux1-tools-redux.json
- nodes.py
- src/bizyair/configs/models.json
- src/bizyair/configs/models.yaml
- src/bizyair/data_types.py
- src/bizyair/nodes_base.py
- tools/convert_to_bizyair.py
[20241122_bizyair_flux_fill_inpaint_out.json](https://github.com/user-attachments/files/17861451/20241122_flux_fill_inpaint_out.1.json)
[20241122_bizyair-flux1-tools-redux.json](https://github.com/user-attachments/files/17861583/bizyair-flux1-tools-redux.json)
[20241122_bizyair-flux1-tools-canny.json](https://github.com/user-attachments/files/17861808/20241122_bizyair-flux1-tools-canny.json)
[20241122_bizyair_flux1_depth.bizyair.json](https://github.com/user-attachments/files/17861954/20241122_bizyair_flux1_depth.json)
> Add Flux1 tools

- examples/bizyair-flux1-tools-redux.json
modify node "☁️BizyAir Apply style model " to "☁️BizyAir Apply style model (simple)"  in bizyair-flux1-tools-redux.json
> modify bizyair-flux1-tools-redux.json

- js/subassembly/tools.js
> [fix]node resize bug

- bizyair_extras/__init__.py
- bizyair_extras/nodes_comfyui_layerstyle_advance.py
- examples/bizyair_text_guided_segment-anything.json
- src/bizyair/commands/processors/prompt_processor.py
- src/bizyair/commands/servers/prompt_server.py
- src/bizyair/configs/models.yaml
- src/bizyair/nodes_base.py
> Add LayerMask: SegmentAnythingUltra V2 node

- README.md
- examples/bizyair-shuttleai_shuttle_3_1_aesthetic.json
- src/bizyair/configs/models.json
- src/bizyair/configs/models.yaml
> Support shuttleai shuttle 3 1 aesthetic

- bizyair_extras/__init__.py
- bizyair_extras/nodes_janus_pro.py
- src/bizyair/configs/models.yaml
> Support Janus_Pro_7B

- src/bizyair/common/client.py
1. send_request方法补充逻辑。当发生ConnectionError时，检查本地代理配置，如果发现存在代理，则提示用户。
2. 目前只检查了环境变量，不确定是否兼容其他代理使用方式，需要测试。
> check proxy envars when connection error occurs

- llm.py
joycaption1 也是用 joycaption2 的后端。统一后端的同时兼容之前的工作流。
> optimize joycaption

- README.md
> update the gif

- prestartup_script.py
- pyproject.toml
> show how to install manually msg when error happens

- backend/bizyengine/bizy_server/api_client.py
- backend/bizyengine/bizy_server/errno.py
- backend/bizyengine/bizy_server/server.py
- backend/bizyengine/bizy_server/stream_response.py
修复chat接口对话轮数过多时超时错误、
单独提取stream_response类，正确释放资源
> add text and image api for BizyBot
